const AITHER_BACKEND='https://aitherbackend.onrender.com';
let currentUser=null;
const auth$=id=>document.getElementById(id);
function authToast(message){const t=document.getElementById('toast');if(!t)return;t.textContent=message;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2600)}
function setAuthView(view){auth$('loginForm').hidden=view!=='login';auth$('registerForm').hidden=view!=='register';auth$('accountView').hidden=view!=='account';auth$('authError').textContent=''}
function renderAccount(user){currentUser=user||null;const button=auth$('accountButton');if(button)button.textContent=user?'👤':'👤';if(user){auth$('accountTitle').textContent=`Welcome, ${user.name}`;auth$('accountEmail').textContent=user.email;auth$('accountVerified').textContent=user.email_verified?'Email verified':'Email not verified';setAuthView('account')}else setAuthView('login')}
async function authRequest(path,options={}){const res=await fetch(`${AITHER_BACKEND}${path}`,{...options,credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})}});let data=null;try{data=await res.json()}catch{}if(!res.ok){const detail=data?.detail;throw new Error(Array.isArray(detail)?detail.map(x=>x.msg).join(', '):detail||`Request failed (${res.status})`)}return data}
async function restoreSession(){try{const data=await authRequest('/api/auth/session',{method:'GET'});renderAccount(data.authenticated?data.user:null)}catch{renderAccount(null)}}
async function registerAccount(e){e.preventDefault();const name=auth$('registerName').value.trim(),email=auth$('registerEmail').value.trim(),password=auth$('registerPassword').value;if(!name||!email||!password)return;const button=auth$('registerSubmit');button.disabled=true;button.textContent='Creating account…';auth$('authError').textContent='';try{const data=await authRequest('/api/auth/register',{method:'POST',body:JSON.stringify({name,email,password})});renderAccount(data.user);authToast('Aither account created')}catch(err){auth$('authError').textContent=err.message}finally{button.disabled=false;button.textContent='Create Account'}}
async function loginAccount(e){e.preventDefault();const email=auth$('loginEmail').value.trim(),password=auth$('loginPassword').value;if(!email||!password)return;const button=auth$('loginSubmit');button.disabled=true;button.textContent='Signing in…';auth$('authError').textContent='';try{const data=await authRequest('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});renderAccount(data.user);authToast('Signed in to Aither')}catch(err){auth$('authError').textContent=err.message}finally{button.disabled=false;button.textContent='Sign In'}}
async function logoutAccount(){try{await authRequest('/api/auth/logout',{method:'POST',body:JSON.stringify({})})}catch{}renderAccount(null);setAuthView('login');authToast('Signed out')}
function openAuth(){auth$('authModal').hidden=false;restoreSession()}function closeAuth(){auth$('authModal').hidden=true}
auth$('accountButton').onclick=openAuth;auth$('closeAuth').onclick=closeAuth;auth$('showRegister').onclick=()=>setAuthView('register');auth$('showLogin').onclick=()=>setAuthView('login');auth$('loginForm').onsubmit=loginAccount;auth$('registerForm').onsubmit=registerAccount;auth$('logoutButton').onclick=logoutAccount;auth$('authModal').addEventListener('click',e=>{if(e.target===auth$('authModal'))closeAuth()});setAuthView('login');restoreSession();
